services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/budget_book

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_book

volumes:
  pgdata:
